### ISSUE TITLE
CI 测试错误

### ISSUE THREAD

**Issue by whybeyoung** [iflytek/AutoSpark#3]
### ⚠️ 请先阅读. ⚠️

- [x] 我已经搜过， 没有找到

### 你在哪个操作系统使用Autospark?

官方Docker 容器

### 使用版本分支?

Main

### 你是使用星火大模型的账号实验的吗？

星火大模型

### bug属于什么分类?

安装使用

### 描述你的问题

<img width="896" alt="image" src="https://github.com/iflytek/AutoSpark/assets/10629930/e40b2a57-876a-42bc-931b-b5a5d4578ad5">
CI test 错误 缺包

### 上传bug日志内容

no

**Comment by Jonyzqw** [comment]
我猜测可能是ci.yml文件在执行代码检查和测试时，未导入autospark_kit等相关依赖包。这个依赖包是应该在分支那边推上来忘记引入还是ci.yml里“name: Install dependencies”缺少autospark_kit等相关依赖包的导入。

**Comment by whybeyoung** [comment]
可以考虑在 ci.yml 里引入
